Alexis workflow
Nicholas-Sliter/lt-app pull request #7
Opened 2022-10-16 13:56 UTC by AlexisBallo2

reservation requests are now working. Getting and returning availability

TODO: add to waitlist.

2022-12-18 15:02 UTC, Nicholas-Sliter commented
I am working through the code, I'll send you updates in a few days

2022-12-21 20:43 UTC, Nicholas-Sliter reviewed
I did some refactoring to simplify and improve code quality.  You should read through ReservationForm, the base page (index.tsx), the api adaptor (/lib/frontend/adaptor), and the new api endpoints (availability and reservations).

2022-12-21 20:43 UTC, Nicholas-Sliter commented on src/pages/api/checkAvail.tsx
>    makeRes,
In general you should avoid making endpoints like this.  Try and follow REST standards. Looking into REST Resource naming conventions

2022-12-21 20:43 UTC, Nicholas-Sliter commented on src/pages/api/makeRes.ts
> +        var waitlistBinary = 0;
I refactored this endpoint into POST:/api/reservations for the same reasons as above.  You also need to make sure you validate your inputs.

The `var` keyword is essentially depreciated in modern JS.  You should use `let` or `const` instead unless you explicitly need variable hoisting.

2022-12-21 20:43 UTC, Nicholas-Sliter commented on src/pages/index.tsx
> +      <Signup languages={languages} courses={courses} />
There is no reason to separate Signup into its own component.  Just put the contents of signup into this return statement.

2022-12-21 20:43 UTC, Nicholas-Sliter commented on src/components/Admin.tsx
> +const languages = [
Use the database for languages, avoid putting this information in code

2022-12-21 20:43 UTC, Nicholas-Sliter commented on src/components/Admin.tsx
> +		var temp = new Date(val.toDateString()).toISOString().split("T")[0];
Remove `var`.  Use the new `stringFormattedDate` function.

2022-12-21 20:43 UTC, Nicholas-Sliter commented on src/components/Header/Header.tsx
> +            {/* {currentPage == "Signup" ? <div onClick={() => updatePage("admin")}>Admin</div> : <div onClick={() => updatePage("Signup")}>Signup</div>} */}
We will just access the admin page from a URL, no need to do this.

2022-12-21 20:46 UTC, Nicholas-Sliter commented on src/pages/api/checkAvail.tsx
> +      for (var i = 0; i < 30; i++) {
Huge no-no here.  Looped DB calls should almost never be used and is very bad for performance.  Look into the "N+1 query problem".  I've refactored this code in the reservations endpoint to work with a single query.  Take a look.

2022-12-21 20:47 UTC, Nicholas-Sliter commented on src/pages/api/getDateInfo.ts
> +    if (req.method == "POST") {
This can be simplified by using the next-connect (nc) package that is installed.  Look at some of the other apis for examples.

2022-12-21 20:49 UTC, Nicholas-Sliter requested changes
Please see my other comments for general code style, performance, and architecture guidelines.  Additionally, make sure to read through the code I have added and let me know if you don't understand any specifics.

2022-12-25 21:02 UTC, Nicholas-Sliter commented
Momentjs is depreciated.  If we need a date library, dayjs is a decent alternative.  But I don't currently see the need for a date library.  Why did you want to use moment?

2022-12-25 22:14 UTC, AlexisBallo2 commented
want to use date library to accuratly convert date string (ex 2022-12-25) to date object. the conversion using new Date(string) causes some irregularities depending on current time (sometimes gives dec 24 at like 8 pm). will look into datejs

2022-12-26 01:03 UTC, Nicholas-Sliter commented
Ah, you should specify a time zone during the date creation otherwise it defaults to GMT if I recall correctly.

2022-12-29 00:27 UTC, Nicholas-Sliter commented
I'm going to merge these changes into main, you should pull and base your new branch off the updated main branch,

2022-12-29 00:27 UTC, merged